### ISSUE TITLE
Negative timestamp

### ISSUE THREAD

**Issue by fundo-moretti** [webapix/dot-net-json-date-formatter#1]
Hi,

Following JSON date raises `InvalidJsonDateString`
```
{
    "Value": "\/Date(-157939200000+0000)\/"
}

```
I think this timestamp is valid, but `preg_match('/Date\((\d+)([+,-]?\d*)\)/', $date, $matches)` does not take negative timestamps into account.

**Comment by zsocakave** [comment]
Hi,

Thank you for your feedback, we fixed it in 1.0.1.
